[package]
name = "cpu_info"
version = "0.1.0"
edition = "2024"

[dependencies]
windows ={ version = "0.62.2", optional = true, features = ["Win32_System_SystemInformation"] }




[features]
default = ["linux"]
linux = []
windows = ["dep:windows"]
